/* tslint:disable */
/* eslint-disable */
/**
 * Online Resume Builder API
 * An API for Online Resume Builder
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { EducationIM } from '../models';
import { EducationUM } from '../models';
import { EducationVM } from '../models';
/**
 * EducationsApi - axios parameter creator
 * @export
 */
export const EducationsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Deletes a specific education item from a resume.
         * @param {string} id Identifier for the education item.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiEducationsIdDelete: async (id: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling apiEducationsIdDelete.');
            }
            const localVarPath = `/api/Educations/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("Authorization")
                    : await configuration.apiKey;
                localVarHeaderParameter["Authorization"] = localVarApiKeyValue;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Retrieves a specific education item in a resume.
         * @param {string} id Identifier for the education item.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiEducationsIdGet: async (id: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling apiEducationsIdGet.');
            }
            const localVarPath = `/api/Educations/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("Authorization")
                    : await configuration.apiKey;
                localVarHeaderParameter["Authorization"] = localVarApiKeyValue;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Updates a specific education item in a resume.
         * @param {string} id Identifier for the education item.
         * @param {EducationUM} [body] Input model for updating the education item.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiEducationsIdPut: async (id: string, body?: EducationUM, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling apiEducationsIdPut.');
            }
            const localVarPath = `/api/Educations/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("Authorization")
                    : await configuration.apiKey;
                localVarHeaderParameter["Authorization"] = localVarApiKeyValue;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Creates a new education item in a resume.
         * @param {EducationIM} [body] Input model for creating a new education item.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiEducationsPost: async (body?: EducationIM, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/Educations`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("Authorization")
                    : await configuration.apiKey;
                localVarHeaderParameter["Authorization"] = localVarApiKeyValue;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * EducationsApi - functional programming interface
 * @export
 */
export const EducationsApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Deletes a specific education item from a resume.
         * @param {string} id Identifier for the education item.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiEducationsIdDelete(id: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<void>>> {
            const localVarAxiosArgs = await EducationsApiAxiosParamCreator(configuration).apiEducationsIdDelete(id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Retrieves a specific education item in a resume.
         * @param {string} id Identifier for the education item.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiEducationsIdGet(id: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<EducationVM>>> {
            const localVarAxiosArgs = await EducationsApiAxiosParamCreator(configuration).apiEducationsIdGet(id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Updates a specific education item in a resume.
         * @param {string} id Identifier for the education item.
         * @param {EducationUM} [body] Input model for updating the education item.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiEducationsIdPut(id: string, body?: EducationUM, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<EducationVM>>> {
            const localVarAxiosArgs = await EducationsApiAxiosParamCreator(configuration).apiEducationsIdPut(id, body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Creates a new education item in a resume.
         * @param {EducationIM} [body] Input model for creating a new education item.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiEducationsPost(body?: EducationIM, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<EducationVM>>> {
            const localVarAxiosArgs = await EducationsApiAxiosParamCreator(configuration).apiEducationsPost(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * EducationsApi - factory interface
 * @export
 */
export const EducationsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @summary Deletes a specific education item from a resume.
         * @param {string} id Identifier for the education item.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiEducationsIdDelete(id: string, options?: AxiosRequestConfig): Promise<AxiosResponse<void>> {
            return EducationsApiFp(configuration).apiEducationsIdDelete(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Retrieves a specific education item in a resume.
         * @param {string} id Identifier for the education item.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiEducationsIdGet(id: string, options?: AxiosRequestConfig): Promise<AxiosResponse<EducationVM>> {
            return EducationsApiFp(configuration).apiEducationsIdGet(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Updates a specific education item in a resume.
         * @param {string} id Identifier for the education item.
         * @param {EducationUM} [body] Input model for updating the education item.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiEducationsIdPut(id: string, body?: EducationUM, options?: AxiosRequestConfig): Promise<AxiosResponse<EducationVM>> {
            return EducationsApiFp(configuration).apiEducationsIdPut(id, body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Creates a new education item in a resume.
         * @param {EducationIM} [body] Input model for creating a new education item.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiEducationsPost(body?: EducationIM, options?: AxiosRequestConfig): Promise<AxiosResponse<EducationVM>> {
            return EducationsApiFp(configuration).apiEducationsPost(body, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * EducationsApi - object-oriented interface
 * @export
 * @class EducationsApi
 * @extends {BaseAPI}
 */
export class EducationsApi extends BaseAPI {
    /**
     * 
     * @summary Deletes a specific education item from a resume.
     * @param {string} id Identifier for the education item.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EducationsApi
     */
    public async apiEducationsIdDelete(id: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<void>> {
        return EducationsApiFp(this.configuration).apiEducationsIdDelete(id, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Retrieves a specific education item in a resume.
     * @param {string} id Identifier for the education item.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EducationsApi
     */
    public async apiEducationsIdGet(id: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<EducationVM>> {
        return EducationsApiFp(this.configuration).apiEducationsIdGet(id, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Updates a specific education item in a resume.
     * @param {string} id Identifier for the education item.
     * @param {EducationUM} [body] Input model for updating the education item.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EducationsApi
     */
    public async apiEducationsIdPut(id: string, body?: EducationUM, options?: AxiosRequestConfig) : Promise<AxiosResponse<EducationVM>> {
        return EducationsApiFp(this.configuration).apiEducationsIdPut(id, body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Creates a new education item in a resume.
     * @param {EducationIM} [body] Input model for creating a new education item.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EducationsApi
     */
    public async apiEducationsPost(body?: EducationIM, options?: AxiosRequestConfig) : Promise<AxiosResponse<EducationVM>> {
        return EducationsApiFp(this.configuration).apiEducationsPost(body, options).then((request) => request(this.axios, this.basePath));
    }
}
