/* tslint:disable */
/* eslint-disable */
/**
 * Online Resume Builder API
 * An API for Online Resume Builder
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { WorkExperienceIM } from '../models';
import { WorkExperienceUM } from '../models';
import { WorkExperienceVM } from '../models';
/**
 * WorkExperienceApi - axios parameter creator
 * @export
 */
export const WorkExperienceApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Deletes work experience information by id.
         * @param {string} id The id of the work experience to delete.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiWorkExperienceIdDelete: async (id: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling apiWorkExperienceIdDelete.');
            }
            const localVarPath = `/api/WorkExperience/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("Authorization")
                    : await configuration.apiKey;
                localVarHeaderParameter["Authorization"] = localVarApiKeyValue;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Gets work experience information by id.
         * @param {string} id Id of the work experience.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiWorkExperienceIdGet: async (id: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling apiWorkExperienceIdGet.');
            }
            const localVarPath = `/api/WorkExperience/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("Authorization")
                    : await configuration.apiKey;
                localVarHeaderParameter["Authorization"] = localVarApiKeyValue;
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Updates work experience information by id.
         * @param {string} id The id of the work experience to update.
         * @param {WorkExperienceUM} [body] The updated work experience model with the new information.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiWorkExperienceIdPut: async (id: string, body?: WorkExperienceUM, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling apiWorkExperienceIdPut.');
            }
            const localVarPath = `/api/WorkExperience/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("Authorization")
                    : await configuration.apiKey;
                localVarHeaderParameter["Authorization"] = localVarApiKeyValue;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Creates a new work experience.
         * @param {WorkExperienceIM} [body] The model containing the information for the work experience.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiWorkExperiencePost: async (body?: WorkExperienceIM, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/WorkExperience`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
                    ? await configuration.apiKey("Authorization")
                    : await configuration.apiKey;
                localVarHeaderParameter["Authorization"] = localVarApiKeyValue;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * WorkExperienceApi - functional programming interface
 * @export
 */
export const WorkExperienceApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Deletes work experience information by id.
         * @param {string} id The id of the work experience to delete.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiWorkExperienceIdDelete(id: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<void>>> {
            const localVarAxiosArgs = await WorkExperienceApiAxiosParamCreator(configuration).apiWorkExperienceIdDelete(id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Gets work experience information by id.
         * @param {string} id Id of the work experience.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiWorkExperienceIdGet(id: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<WorkExperienceVM>>> {
            const localVarAxiosArgs = await WorkExperienceApiAxiosParamCreator(configuration).apiWorkExperienceIdGet(id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Updates work experience information by id.
         * @param {string} id The id of the work experience to update.
         * @param {WorkExperienceUM} [body] The updated work experience model with the new information.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiWorkExperienceIdPut(id: string, body?: WorkExperienceUM, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<WorkExperienceVM>>> {
            const localVarAxiosArgs = await WorkExperienceApiAxiosParamCreator(configuration).apiWorkExperienceIdPut(id, body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary Creates a new work experience.
         * @param {WorkExperienceIM} [body] The model containing the information for the work experience.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiWorkExperiencePost(body?: WorkExperienceIM, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<WorkExperienceVM>>> {
            const localVarAxiosArgs = await WorkExperienceApiAxiosParamCreator(configuration).apiWorkExperiencePost(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * WorkExperienceApi - factory interface
 * @export
 */
export const WorkExperienceApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @summary Deletes work experience information by id.
         * @param {string} id The id of the work experience to delete.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiWorkExperienceIdDelete(id: string, options?: AxiosRequestConfig): Promise<AxiosResponse<void>> {
            return WorkExperienceApiFp(configuration).apiWorkExperienceIdDelete(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Gets work experience information by id.
         * @param {string} id Id of the work experience.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiWorkExperienceIdGet(id: string, options?: AxiosRequestConfig): Promise<AxiosResponse<WorkExperienceVM>> {
            return WorkExperienceApiFp(configuration).apiWorkExperienceIdGet(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Updates work experience information by id.
         * @param {string} id The id of the work experience to update.
         * @param {WorkExperienceUM} [body] The updated work experience model with the new information.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiWorkExperienceIdPut(id: string, body?: WorkExperienceUM, options?: AxiosRequestConfig): Promise<AxiosResponse<WorkExperienceVM>> {
            return WorkExperienceApiFp(configuration).apiWorkExperienceIdPut(id, body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Creates a new work experience.
         * @param {WorkExperienceIM} [body] The model containing the information for the work experience.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiWorkExperiencePost(body?: WorkExperienceIM, options?: AxiosRequestConfig): Promise<AxiosResponse<WorkExperienceVM>> {
            return WorkExperienceApiFp(configuration).apiWorkExperiencePost(body, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * WorkExperienceApi - object-oriented interface
 * @export
 * @class WorkExperienceApi
 * @extends {BaseAPI}
 */
export class WorkExperienceApi extends BaseAPI {
    /**
     * 
     * @summary Deletes work experience information by id.
     * @param {string} id The id of the work experience to delete.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WorkExperienceApi
     */
    public async apiWorkExperienceIdDelete(id: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<void>> {
        return WorkExperienceApiFp(this.configuration).apiWorkExperienceIdDelete(id, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Gets work experience information by id.
     * @param {string} id Id of the work experience.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WorkExperienceApi
     */
    public async apiWorkExperienceIdGet(id: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<WorkExperienceVM>> {
        return WorkExperienceApiFp(this.configuration).apiWorkExperienceIdGet(id, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Updates work experience information by id.
     * @param {string} id The id of the work experience to update.
     * @param {WorkExperienceUM} [body] The updated work experience model with the new information.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WorkExperienceApi
     */
    public async apiWorkExperienceIdPut(id: string, body?: WorkExperienceUM, options?: AxiosRequestConfig) : Promise<AxiosResponse<WorkExperienceVM>> {
        return WorkExperienceApiFp(this.configuration).apiWorkExperienceIdPut(id, body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @summary Creates a new work experience.
     * @param {WorkExperienceIM} [body] The model containing the information for the work experience.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WorkExperienceApi
     */
    public async apiWorkExperiencePost(body?: WorkExperienceIM, options?: AxiosRequestConfig) : Promise<AxiosResponse<WorkExperienceVM>> {
        return WorkExperienceApiFp(this.configuration).apiWorkExperiencePost(body, options).then((request) => request(this.axios, this.basePath));
    }
}
