/* tslint:disable */
/* eslint-disable */
/**
 * Online Resume Builder API
 * An API for Online Resume Builder
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface PersonalInfoIdBody
 */
export interface PersonalInfoIdBody {
    /**
     * 
     * @type {string}
     * @memberof PersonalInfoIdBody
     */
    fullName: string;
    /**
     * 
     * @type {string}
     * @memberof PersonalInfoIdBody
     */
    address: string;
    /**
     * 
     * @type {string}
     * @memberof PersonalInfoIdBody
     */
    phoneNumber: string;
    /**
     * 
     * @type {string}
     * @memberof PersonalInfoIdBody
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof PersonalInfoIdBody
     */
    summary: string;
    /**
     * 
     * @type {Blob}
     * @memberof PersonalInfoIdBody
     */
    personImage?: Blob;
}
