/* tslint:disable */
/* eslint-disable */
/**
 * Online Resume Builder API
 * An API for Online Resume Builder
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface UserUM
 */
export interface UserUM {
    /**
     * 
     * @type {string}
     * @memberof UserUM
     */
    firstName: string | undefined;
    /**
     * 
     * @type {string | undefined}
     * @memberof UserUM
     */
    lastName: string | undefined;
    /**
     * 
     * @type {string | undefined}
     * @memberof UserUM
     */
    email: string | undefined;
}
